# -*- coding: utf-8 -*-
"""LinAlg_Lab10_Arcera.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10Wmi2dOFPhYfy1nb-WbEZtrA0JIMSNUc

# **Arcera, Edhnaer**
## Laboratory 10 : Linear Transformations

## **Supplementary Activity** 

Try to implement the linear transformations using spancs using the scatteplot view. Just do at least one example of linear transformation for a 2D space.
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
# %matplotlib inline

def plot_quiv(x,t_mat=np.eye(2)):
    A = x @ t_mat
    print(A)
    size = (5,5)
    plt.figure(figsize=(4,4))
    plt.xlim(-size[0],size[0])
    plt.ylim(-size[1],size[1])
    plt.scatter(A[0],A[1], color='red')
    plt.grid()
    plt.show()

E = np.array([
    [1, 3],
    [0, 1]
])

scale = np.array([
    [4,0],
    [0,1]
])
print("Before Scaling")
plot_quiv(E)
print("After Scaling")
plot_quiv(E, scale)